### ISSUE TITLE
Remove MR Tracking not working with XRRig

### ISSUE THREAD

**Issue by ndgreen** [TonyViT/MrcXrtHelpers#1]
Remove MR Camera Tracking doesn't seem to be working with Track Pose Driver (new input system) on the XRRig. Head movement is still moving the OVRCamera in MR.

**Comment by TonyViT** [comment]
Yes, a girl told me how to solve this, and I have reported the news on [my blog article](https://skarredghost.com/2021/07/10/how-to-oculus-mixed-reality-capture-mrc-unity/):
I’m using Unity 2020.3 and Action Based XR Interaction Toolkit. At first, I found the problem where the camera keeps following my headset rotation when I turned on the OBS Studio. After debugging for several hours, I found the problem and fixed it.  You just need to change the import library from using UnityEngine.SpatialTracking to UnityEngine.InputSystem.XR on RemoveMRCamerasTracking.cs I hope it can help other people too who encounter the same problem

Let me know if this works. If it works, maybe I can add both files to the repo

**Comment by ndgreen** [comment]
That does stop the camera from spinning. Strangely it does not take the  orientation of the camera as positioned in the scene but the orientation of the camera when it was dropped into the scene (prior to rotation). Also it has some blips still to what you are looking at (maybe every second or 2. Most likely this is in var waiter . I'll play around with it and let you know.

Thanks for the help
